---
alias: Atmospheric Manager
id: "1739163441114"
description: ""
triggers:
  - trigger: numeric_state
    entity_id:
      - sensor.office_air_quality_index
    below: 50
    id: turn_off
    for:
      hours: 0
      minutes: 5
      seconds: 0
  - trigger: numeric_state
    entity_id:
      - sensor.office_air_quality_index
    above: 50
    id: turn_on
    for:
      hours: 0
      minutes: 1
      seconds: 0
actions:
  - action: switch.{{ trigger.id if trigger.id is defined else 'toggle' }}
    target:
      entity_id: switch.air_filter
