---
alias: Test Notification
id: "1759856160073"
description: ""
triggers: []
conditions: []
actions:
  - action: notify.send_message
    metadata: {}
    data:
      message: Test Notification
mode: single
