---
# Common Control Inputs
# Shared helpers used across multiple packages

input_boolean:
  vacation_mode:
    name: "Vacation Mode"
    icon: mdi:beach

input_number:
  sleep_temperature:
    name: "Sleep Temperature"
    min: 60
    max: 80
    step: 1
    unit_of_measurement: "°F"
    icon: mdi:thermometer

  awake_temperature:
    name: "Awake Temperature"
    min: 60
    max: 80
    step: 1
    unit_of_measurement: "°F"
    icon: mdi:thermometer

  away_temperature:
    name: "Away Temperature"
    min: 60
    max: 80
    step: 1
    unit_of_measurement: "°F"
    icon: mdi:thermometer

binary_sensor:
  - platform: tod
    name: "Sleep Schedule"
    after: "22:00"
    before: "07:00"
