---
# DevOps automation configuration
# Handles automatic updates and configuration deployment

shell_command:
  # Pull latest changes from git repository
  git_pull: 'cd /config && git pull origin main'

automation:
  - id: auto_deploy_config
    alias: "Deploy Configuration Updates"
    description: "Automatically deploy configuration changes when GitHub Actions validation passes"

    trigger:
      # Triggered by webhook from GitHub Actions after successful validation
      - platform: webhook
        webhook_id: deploy_config
        allowed_methods:
          - POST
        local_only: false

    action:
      - try:
          # Pull latest changes
          - service: shell_command.git_pull
            response_variable: git_response

          # Reload core configuration to apply changes
          - service: homeassistant.reload_all

          # Send success notification
          - service: notify.all_devices
            data:
              title: "Configuration Deployment Complete"
              message: >-
                Deployed commit {{ trigger.json.commit[:7] }}: {{ trigger.json.message }}
        error:
          # Send failure notification
          - service: notify.all_devices
            data:
              title: "Configuration Deployment Failed"
              message: >-
                Failed to deploy commit {{ trigger.json.commit[:7] }}: {{ trigger.json.message }}

  - id: automatic_updates
    alias: "Automatic Updates"
    description: "Automatically install available updates daily at 4 AM"

    triggers:
      - trigger: time
        at: 04:00:00

    actions:
      - try:
          - action: update.install
            target:
              entity_id: >-
                {{ states.update | map(attribute='entity_id') |
                   select('is_state', 'on') | list }}
        error:
          # Send failure notification
          - service: notify.low_priority
            data:
              title: "Automatic Updates Failed"
              message: "Failed to install available updates"
