---
# HVAC Intelligent Climate Control Package
# Controls 4 Daikin heat exchanger units with air quality integration,
# vacation mode, and adaptive scheduling with temperature prediction.
# See specs/hvac.md for detailed specification

# ============================================================================
# INPUT HELPERS
# ============================================================================

input_boolean:
  hvac_automation_enabled:
    name: "HVAC Automation Enabled"
    icon: mdi:hvac

# ============================================================================
# AUTOMATIONS
# ============================================================================

automation:
  - alias: "HVAC Automated Control"
    id: hvac_automated_control
    description: "Automatically apply HVAC priority rules when conditions change"
    triggers:
      # Priority 1: Air Quality changes
      - trigger: numeric_state
        entity_id: sensor.main_floor_aqi
        above: 99
        id: aqi_high
      - trigger: numeric_state
        entity_id: sensor.main_floor_aqi
        below: 100
        id: aqi_normal

      # Priority 2: Vacation Mode changes
      - trigger: state
        entity_id: input_boolean.vacation_mode
        id: vacation_mode

      # Priority 3 & 4: Sleep/Awake schedule
      - trigger: state
        entity_id: binary_sensor.sleep_schedule
        to: "on"
        id: sleep_start
      - trigger: state
        entity_id: binary_sensor.sleep_schedule
        to: "off"
        id: awake_start

      # Automation enabled
      - trigger: state
        entity_id: input_boolean.hvac_automation_enabled
        to: "on"
        id: automation_enabled

      # Temperature settings changed
      - trigger: state
        entity_id:
          - input_number.sleep_temperature
          - input_number.awake_temperature
          - input_number.away_temperature
        id: temperature_changed

    conditions:
      - condition: state
        entity_id: input_boolean.hvac_automation_enabled
        state: "on"

    actions:
      # Add delay for temperature changes to avoid rapid updates
      - choose:
          - conditions:
              - condition: trigger
                id: temperature_changed
            sequence:
              - delay:
                  seconds: 2
        default: []

      # Determine target mode and temperature based on priority rules
      - choose:
          # Priority 1: Air Quality - Fan mode when AQI >= 100
          - conditions:
              - condition: numeric_state
                entity_id: sensor.main_floor_aqi
                above: 99
            sequence:
              # Turn on fan mode for units with air filters
              - action: climate.set_hvac_mode
                target:
                  entity_id:
                    - climate.faikin_living_mqtt_hvac
                    - climate.faikin_guest_mqtt_hvac
                data:
                  hvac_mode: fan
              # Turn off other units to save energy
              - action: climate.turn_off
                target:
                  entity_id:
                    - climate.faikin_master_mqtt_hvac
                    - climate.faikin_basement_mqtt_hvac

          # Priority 2: Vacation Mode - Auto mode at away temperature
          - conditions:
              - condition: state
                entity_id: input_boolean.vacation_mode
                state: "on"
            sequence:
              - action: climate.set_temperature
                target:
                  entity_id:
                    - climate.faikin_living_mqtt_hvac
                    - climate.faikin_master_mqtt_hvac
                    - climate.faikin_basement_mqtt_hvac
                    - climate.faikin_guest_mqtt_hvac
                data:
                  hvac_mode: auto
                  temperature: "{{ states('input_number.away_temperature') | float(70) }}"

          # Priority 3: Sleep Mode - Cool mode at sleep temperature
          - conditions:
              - condition: state
                entity_id: binary_sensor.sleep_schedule
                state: "on"
            sequence:
              # Turn on bedroom units
              - action: climate.set_temperature
                target:
                  entity_id:
                    - climate.faikin_master_mqtt_hvac
                    - climate.faikin_guest_mqtt_hvac
                data:
                  hvac_mode: cool
                  temperature: "{{ states('input_number.sleep_temperature') | float(68) }}"
              # Turn off other units to save energy
              - action: climate.turn_off
                target:
                  entity_id:
                    - climate.faikin_living_mqtt_hvac
                    - climate.faikin_basement_mqtt_hvac

        # Priority 4 (Default): Awake Mode - Auto mode at awake temperature
        default:
          - action: climate.set_temperature
            target:
              entity_id:
                - climate.faikin_living_mqtt_hvac
                - climate.faikin_basement_mqtt_hvac
            data:
              hvac_mode: auto
              temperature: "{{ states('input_number.awake_temperature') | float(71) }}"
          # Turn off other units to save energy
          - action: climate.turn_off
            target:
              entity_id:
                - climate.faikin_master_mqtt_hvac
                - climate.faikin_guest_mqtt_hvac
