---
# Leak Detection
# Detects leaks and sends a warning message when detected.

automation:
  - id: leak_alert
    alias: "Leak Alert"
    description: "Sends warning notifications when moisture is detected"
    mode: single

    triggers:
      - trigger: state
        entity_id: update.bathroom_leak_sensor
        to: "on"
    actions:
      - service: notify.all_devices
        data:
          title: "Bathroom Water Leak Detected"
          message: "Leak detected in the bathroom"
