---
# Leak Detection
# Detects leaks and sends a warning message when detected.

automation:
  - id: leak_alert
    alias: "Leak Alert"
    description: "Sends warning notifications when moisture is detected"
    mode: parallel

    triggers:
      - trigger: template
        value_template: >
          {{ states.binary_sensor
             | selectattr('entity_id', 'search', '_leak_sensor_water_leak')
             | selectattr('state', 'eq', 'on')
             | list | count > 0 }}

    variables:
      triggered_sensor: >
        {{ states.binary_sensor
           | selectattr('entity_id', 'search', '_leak_sensor_water_leak')
           | selectattr('state', 'eq', 'on')
           | map(attribute='entity_id')
           | list | first | default('unknown') }}
      location: >
        {% if '_leak_sensor' in triggered_sensor %}
        {{ triggered_sensor.split('.')[1].split('_leak_sensor')[0] | replace('_', ' ') | title }}
        {% else %}
        Unknown
        {% endif %}

    actions:
      - service: notify.all_devices
        data:
          title: "Water Leak Detected ({{ location }})!"
          message: >
            {% if location == 'Unknown' %}
            A leak was detected in an unkown location!
            {% else %}
            A leak in the {{ location }} was detected!
            {% endif %}

  - id: leak_battery
    alias: "Leak Sensor Battery Alert"
    description: "Sends an alert when leak sensors are low on battery"
    mode: parallel

    triggers:
      - trigger: template
        value_template: >
          {{ states.binary_sensor
             | selectattr('entity_id', 'search', '_leak_sensor_battery_low')
             | selectattr('state', 'eq', 'on')
             | list | count > 0 }}

    variables:
      triggered_sensor: >
        {{ states.binary_sensor
           | selectattr('entity_id', 'search', '_leak_sensor_battery_low')
           | selectattr('state', 'eq', 'on')
           | map(attribute='entity_id')
           | list | first | default('unknown') }}
      location: >
        {% if '_leak_sensor' in triggered_sensor %}
        {{ triggered_sensor.split('.')[1].split('_leak_sensor')[0] | replace('_', ' ') | title }}
        {% else %}
        Unknown
        {% endif %}

    actions:
      - service: notify.all_devices
        data:
          title: "{{ location }} Leak Detector Reports Low Battery"
          message: >
            {% if location == 'Unknown' %}
            A leak detector is reporting low battery; please see Home Assistant for more details
            {% else %}
            The {{ location }} leak detector is reporting low battery. Due to this, future incidents from {{ location }} may fail to be reported
            {% endif %}
